services:
  - type: web
    name: streamhub
    env: static
    rootDir: react-youtube-clone
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
